# Environment configuration
settings:
  docker:
    parent_image: public.ecr.aws/f7g3v0f1/zenml:deployments
    requirements: requirements.txt
    environment:
      WANDB_DISABLED: "true"

# Model Control Plane configuration
model:
  name: YeOldeEnglishTranslator
  description: Model to translate from old to modern english
  tags: ["quickstart", "llm", "t5"]

# Configure the pipeline
parameters:

# Per step configuration
steps:

# Init hook configuration
on_init_kwargs:
  model_name: model
  tokenizer_name: tokenizer