# Environment configuration
settings:
  docker:
    parent_image: public.ecr.aws/f7g3v0f1/zenml:deployments
    requirements: requirements.txt
    environment:
      WANDB_DISABLED: "true"

  orchestrator.sagemaker:
    instance_type: ml.m5.4xlarge

# Model Control Plane configuration
model:
  name: YeOldeEnglishTranslator
  description: Model to translate from old to modern english
  tags: ["quickstart", "llm"]

# Configure the pipeline
parameters:
  data_url: 'https://storage.googleapis.com/zenml-public-bucket/quickstart-files/translations.txt'
  # model_type: "t5-small"  # Choose between t5-small and t5-large
  num_train_epochs: 2
  per_device_train_batch_size: 4
  gradient_accumulation_steps: 1
  dataloader_num_workers: 0


# Per step configuration
steps:
  split_dataset:
    parameters:
      subset_size: 0.5  # only use 50% of all available data
      train_size: 0.7
      test_size: 0.1
      eval_size: 0.2
      random_state: 42
