# Serving pipeline configuration
model:
  name: breast_cancer_classifier
  version: production

# Pipeline settings
enable_cache: false
enable_artifact_metadata: true
enable_artifact_visualization: true
enable_step_logs: true

# Step configurations
steps:
  serving_predict:
    enable_cache: false